[package]
name = "smoltcp-nal"
version = "0.1.0"
authors = ["Ryan Summers <ryan.summers@vertigo-designs.com>"]
edition = "2018"
license = "MIT"
description = "embedded-nal implementation for smoltcp"
keywords = ["smoltcp", "embedded-nal", "tcp"]
categories = ["network-programming", "no-std"]
repository = "https://github.com/quartiq/smoltcp-nal.git"

[dependencies]
heapless = "0.6.1"
embedded-nal = "0.1"

[dependencies.nanorand]
version = "0.5.2"
default-features = false
features = ["wyrand"]

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp"
branch = "dhcp-socket"
features = ["medium-ethernet", "proto-ipv6", "socket-tcp", "socket-dhcpv4"]
default-features = false
